# -*- coding: utf-8 -*-
"""Student Mark Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJyyBz2EOVGVMN-UYuCTnJuI2cjIap90
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

#dataset generator
import csv
import random

# Number of samples
num_samples = 100

with open("student_marks.csv", "w", newline="") as file:
    writer = csv.writer(file)

    # Header
    writer.writerow(["Hours_Studied", "Attendance", "Internal_Marks", "Final_Marks"])

    for _ in range(num_samples):
        hours = random.randint(0, 10)              # hours studied per day
        attendance = random.randint(40, 100)       # attendance %
        internal = random.randint(5, 30)           # internal marks out of 30

        # Final marks depends on performance (realistic relation)
        final = int(
            5*hours +
            0.4*attendance +
            1.2*internal +
            random.randint(-5, 5)   # noise
        )

        final = max(0, min(final, 100))  # clamp between 0–100

        writer.writerow([hours, attendance, internal, final])

print("student_marks.csv with 100 samples created!")

#load dataset
data = pd.read_csv("student_marks.csv")
print(data.head())
print(data.describe())
print(data.isnull().sum())

#split dataset
X = data[['Hours_Studied', 'Attendance', 'Internal_Marks']]
y = data['Final_Marks']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#predict dataset
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"MSE: {mse}")
print(f"R2 Score: {r2}")

# New Student prediction
new_student = [[6, 85, 22]]
predicted_marks = model.predict(new_student)
print(f"Predicted Final Marks: {predicted_marks[0]:.2f}")